name: particles_flutter
description: >-
  A flutter package for particle animation. You can control the animation speed, number of Particles on the screen, dimension and shape of particle via connecting lines,etc.
version: 0.1.4
author: Raja Jain<rajajain08@gmail.com>
homepage: https://github.com/rajajain08/particles_flutter/tree/master/particles_flutter
issue_tracker: https://github.com/rajajain08/particles_flutter/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
